<?php
/**
* @file
* Mobile Content module allows content administrator to tag sections of 
* content to be displayed on mobile devices. Tag format should be {mobile}...{/mobile}. 
* Powerful module to display different content based on the browsing device.
*
* Module Support: http://www.DrupalCMSCoder.com
*
* @author 
* Danny Najm <danny@DrupalCMSCoder.com>
*
*/

require_once('mobile_detect.php');

/*
* Generates an array for rendering the given node.
* @author 
* Danny Najm <danny@DrupalCMSCoder.com>
*/
function mobile_content_node_view($node, $view_mode, $langcode) {
	$node->title = _mobile_content_filter_for_display($node->title);
	$node->body['und'][0]['value'] = $node->content['body'][0]['#markup'] = _mobile_content_filter_for_display($node->content['body'][0]['#markup']);
}

/*
* Filter content for display on device.
* @author 
* Danny Najm <danny@DrupalCMSCoder.com>
*/
function _mobile_content_filter_for_display($original_node) {
	$pattern = "/\{mobile\}(.*)\{\/mobile\}/sU";
	$user_agent = $_SERVER['HTTP_USER_AGENT'];
	if (preg_match_all($pattern, $original_node, $matches)) {
		$detect = new Mobile_Detect;
		$deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'phone') : 'computer');
		if ($deviceType != 'computer') {
			$new_node = '';
			foreach ($matches[1] as $match)
				$new_node .= $match . ' ';
			return $new_node;
		} else {
			return str_replace('{/mobile}', '', str_replace('{mobile}', '', $original_node));	
		}
	}
	return $original_node;
}

/**
* Implement hook_theme().
*/
function mobile_content_theme() {
  return array(
    'mobile_content_preprocess_html' => array(
      'arguments' => array('vars' => NULL),
    ),
  );
}

/**
* Implement hook_preprocess_html().
* @author 
* Danny Najm <danny@DrupalCMSCoder.com>
*/
function mobile_content_preprocess_html(&$vars) {
	$head_title_array = $vars['head_title_array'];
	$vars['head_title'] = _mobile_content_filter_for_display($vars['head_title']);
	(isset($head_title_array['title'])) ? $title = _mobile_content_filter_for_display($head_title_array['title']) : $title = $vars['head_title'];
	$vars['head_title_array'] = array(
			'title' => $title,
			'name' => _mobile_content_filter_for_display($head_title_array['name']),
		);
	drupal_set_title($title);
}

/**
* Implements hook_preprocess_page().
* @author 
* Danny Najm <danny@DrupalCMSCoder.com>
*/
function mobile_content_preprocess_page(&$vars) {
	if (isset($vars['node']))
		drupal_set_title($vars['node']->title);
}

/**
* Returns HTML for a breadcrumb trail.
* @author 
* Danny Najm <danny@DrupalCMSCoder.com>
*/
function mobile_content_menu_breadcrumb_alter(&$active_trail, $item) {
	$a_trail = array();
	foreach($active_trail as $trail) {
		if (isset($trail['title']))
			$trail['title'] = _mobile_content_filter_for_display($trail['title']);
		array_push($a_trail, $trail);
	}
	$active_trail = $a_trail;
}